package br.edu.unifei.ecot12.bleach;

public class Main {
    public static void main(String[] args) {
        Vaizard v1 = new Vaizard();
        Zampakuto z1 = new Zampakuto();
        SoulSociety sou = SoulSociety.getInstance();
        sou.getInhabtants().add(v1);
        sou.getDistricts().add("Sereitei");
        v1.setName("Shinji Hirako");
        v1.setAlive(true);
        v1.setPowerLevel(200);
        v1.setLife(100);
        v1.setDefense(100);
        v1.setReiatsu(150);
        v1.setMaskForm("Faráoh");
        v1.setTimeWithMask(3);
        v1.setAppearance("Blond");
        v1.setSpecialty("Fencing");
        v1.setHaveGigai(false);
        z1.setName("Sakanade");
        v1.setZampakuto(z1);
        v1.setHome(sou);
        System.out.println("-----Vaizard-----");
        System.out.println(v1.getName());
        System.out.println(v1.getDefense());
        System.out.println(v1.getReiatsu());
        System.out.println(v1.getAppearance());
        System.out.println(v1.getZampakuto().getName());
        System.out.println(v1.getHome());
        System.out.println("-----Using Hollow Mask-----");
        v1.activateHollowMask();
        System.out.println(v1.getName());
        System.out.println(v1.getDefense());
        System.out.println(v1.getReiatsu());
        System.out.println(v1.getAppearance());

        NormalShinigami s1 = new NormalShinigami();
        SoulSociety sou2 = SoulSociety.getInstance();
        sou2.getDistricts().add("Rukongai");
        s1.setName("Kenpachi Zaraki");
        s1.setPowerLevel(150);
        s1.setLife(100);
        s1.setDefense(80);
        s1.setReiatsu(150);
        s1.setCurrentMission("Patrol");
        s1.setRank("Captain");
        s1.setAlive(true);
        Zampakuto z2 = new Zampakuto();
        Division d1 = new Division();
        z2.setName("Norazashi");
        d1.setNumber(11);
        d1.setSpecialty("Combat");
        d1.getMembers().add(s1);
        d1.setCaptain(s1);
        s1.setDivision(d1);
        s1.setZampakuto(z2);
        s1.setHome(sou2);
        NormalShinigami s2 = new NormalShinigami();
        s2.setName("Ikkaku Madarame");
        s2.setPowerLevel(90);
        s2.setLife(90);
        s2.setDefense(50);
        s2.setReiatsu(100);
        s2.setCurrentMission("Patrol");
        s2.setRank("3 on command");
        s2.setDivision(d1);
        s2.setAlive(true);
        d1.getMembers().add(s2);
        Zampakuto z3 = new Zampakuto();
        z3.setName("Hozukimaru");
        s2.setZampakuto(z3);
        Attack att1 = new Attack();
        att1.setDamageAmout(8);
        Kido k1 = new Kido(att1);
        k1.setName("Hado 33: Sokatsui");
        k1.setReiatsuCost(5);
        s2.getAbilities().add(k1);
        s1.getAbilities().add(k1);
        System.out.println("-----Normal Shinigami-----");
        System.out.println(s1.getName());
        System.out.println(s1.getZampakuto().getName());
        System.out.println(s1.getDivision().getNumber());
        System.out.println(s2.getName());
        System.out.println(s2.getZampakuto().getName());
        System.out.println(s2.getDivision().getNumber());
        System.out.println(s1.getHome());
        sou2.getInhabtants().add(s1);
        sou2.getInhabtants().add(s2);
        sou2.getDivisions().add(d1);

        Human h1 = new Human();
        HumanWorld hw = HumanWorld.getInstance();
        h1.setName("Orihime Inoue");
        h1.setAppearance("Red-haired");
        h1.setPowerLevel(5);
        h1.setDefense(5);
        h1.setLife(15);
        h1.setSpiritualAwareness(true);
        h1.setPhysycalStrength(15);
        h1.setOccupattion("Student");
        h1.setReiatsu(100);
        h1.setAlive(true);
        Healing he = new Healing();
        he.setHealAmount(30);
        Special sp1 = new Special(he);
        sp1.setName("Soten Kisshum");
        sp1.setSpecialEffect("Orange healing block");
        sp1.setReiatsuCost(15);
        Defense de = new Defense();
        de.setReduceDemage(20);
        Buff sp2 = new Buff(de);
        sp2.setName("Santen Keshum");
        sp2.setAffectedAtribute("Deffense skills");
        sp2.setReiatsuCost(15);
        h1.getAbilities().add(sp1);
        h1.getAbilities().add(sp2);
        h1.setHome(hw);
        hw.getInhabtants().add(h1);
        System.out.println("-----Human-----");
        System.out.println(h1.getName());
        System.out.println(h1.getHome());
        System.out.println(h1.getReiatsu());
        System.out.println("Abilities:");
        for(Ability a : h1.getAbilities()) System.out.println(a.getName());

        Quincy q1 = new Quincy();
        HumanWorld hw1 = HumanWorld.getInstance();
        q1.setName("Uryu Ishida");
        q1.setSpiritualAwareness(true);
        q1.setOccupattion("Doctor");
        q1.setSpiritualWeapon("Laiden Hant");
        q1.setWeaponLevel(15);
        q1.setHome(hw1);
        q1.setAlive(true);
        hw1.getInhabtants().add(q1);
        System.out.println("-----Quincy-----");
        System.out.println(q1.getName());
        System.out.println(q1.getOccupattion());
        System.out.println(q1.getSpiritualWeapon());
        System.out.println(q1.getHome());

        SubstituteShinigami sub = new SubstituteShinigami();
        sub.setName("Ichigo Kurosaki");
        sub.setAppearance("Red-haired, average height");
        sub.setPowerLevel(180);
        sub.setLife(100);
        sub.setDefense(75);
        sub.setReiatsu(150);
        sub.setAlive(true);
        HumanWorld hw3 = HumanWorld.getInstance();
        sub.setHome(hw3);
        hw3.getInhabtants().add(sub);
        Zampakuto z4 = new Zampakuto();
        z4.setName("Zangetsu");
        sub.setZampakuto(z4);
        Attack att3 = new Attack();
        att3.setDamageAmout(85);
        Special s3 = new Special(att3);
        s3.setName("Getsuga Tensho");
        s3.setReiatsuCost(20);
        Attack att4 = new Attack();
        att4.setDamageAmout(200);
        Special s4 = new Special(att4);
        s4.setReiatsuCost(100);
        s4.setName("Gray Rey Cero Getsuga Tensho");
        sub.getAbilities().add(s3);
        sub.getAbilities().add(s4);
        System.out.println("-----SubstituteShinigami");
        System.out.println(sub.getName());
        System.out.println(sub.getAppearance());
        System.out.println(z4.getState());
        System.out.println("Abilities:");
        for(Ability a : sub.getAbilities()) System.out.println(a.getName());
        System.out.println("(((shinigami transformation)))");
        sub.transformationShinigami();
        System.out.println(sub.getAppearance());
        z4.setPowerLevel(60);
        z4.liberation(sub);
        System.out.println(z4.getState());
        z4.setPowerLevel(110);
        z4.liberation(sub);
        sub.useBankai();
        System.out.println(z4.getState());
        System.out.println("(((back to human)))");
        sub.returnToHumanBody();
        System.out.println(sub.getAppearance());
        
        Hollow ho1 = new Hollow();
        ho1.setName("GrandFisher");
        ho1.setAppearance("Large, with a human-like lure");
        ho1.setMaskForm("Skull");
        ho1.setType("Commum Hollow");
        ho1.setCanTalk(true);
        ho1.setAlive(true);
        System.out.println("-----Hollow-----");
        System.out.println(ho1.getName());
        System.out.println(ho1.getAppearance());
        System.out.println(ho1.getMaskForm());
        System.out.println(ho1.getType());
        HuecoMundo hueco = HuecoMundo.getInstance();
        hueco.getInhabtants().add(ho1);

        Arrancar ar1 = new Arrancar();
        ar1.setName("Luppi Antenor");
        ar1.setAppearance("Slim, black hair");
        ar1.setMaskForm("Bird");
        ar1.setMaskFragment("Top of head");
        ar1.setAlive(true);
        Zampakuto z5 = new Zampakuto();
        z5.setName("Trepadora");
        ar1.setZampakuto(z5);
        HuecoMundo hueco2 = HuecoMundo.getInstance();
        hueco2.getInhabtants().add(ar1);
        System.out.println("-----Arrancar-----");
        System.out.println(ar1.getName());
        System.out.println(ar1.getAppearance());
        System.out.println(ar1.getMaskForm());
        System.out.println(ar1.getMaskFragment());
        System.out.println(ar1.getZampakuto().getName());
        
        Espada e1 = new Espada();
        e1.setName("Ulquiorra Cifer");
        e1.setAppearance("Tall, green eyes");
        e1.setPowerLevel(180);
        e1.setLife(100);
        e1.setDefense(75);
        e1.setReiatsu(150);
        e1.setNumber(4);
        e1.setTatooLocation("Chest");
        e1.setAspectOfDeath("Emptiness");
        e1.setAlive(true);
        hueco2.getInhabtants().add(e1);
        Attack att2 = new Attack();
        att2.setDamageAmout(95);
        Cero c1 = new Cero(att2);
        c1.setName("Oscuras");
        c1.setReiatsuCost(50);
        e1.getAbilities().add(c1);
        Zampakuto z6 = new Zampakuto();
        z6.setName("Murciélago");
        e1.setZampakuto(z6);
        System.out.println("-----Espada-----");
        System.out.println(e1.getName());
        System.out.println(e1.getAppearance());
        System.out.println(e1.getZampakuto().getName());
        System.out.println(z6.getState());
        z6.setPowerLevel(60);
        z6.liberation(e1);
        System.out.println(z6.getState());
        System.out.println("Abilities");
        for(Ability a : e1.getAbilities()) System.out.println(a.getName());
        System.out.println("(((resurreccion form)))");
        z6.setPowerLevel(120);
        z6.liberation(e1);
        System.out.println(z6.getState());
        System.out.println(e1.getAppearance());

        Confront con = new Confront();
        con.setAttacker(e1);
        con.setTarget(sub);
        con.setAttackerPower(c1);
        con.setGoal("Rescue Orihime");
        System.out.println("-----Confront-----");
        System.out.println("Ulquiorra attacks Kurosaki Ichigo");
        System.out.println("Goal:" + con.getGoal());
        System.out.println(con.getAttacker().getName() + " before first confront:");
        System.out.println(con.getAttacker().getLife());
        System.out.println(con.getAttacker().getDefense());
        System.out.println(con.getAttacker().getReiatsu());
        System.out.println("Alive: "+ con.getAttacker().isAlive());
        System.out.println(con.getTarget().getName() + " before first confront:");
        System.out.println(con.getTarget().getLife());
        System.out.println(con.getTarget().getDefense());
        System.out.println(con.getTarget().getReiatsu());
        System.out.println("Alive: "+ con.getTarget().isAlive());
        System.out.println(con.getAttacker().getName() + " uses " + con.getAttackerPower().getName());
        con.action();
        System.out.println(con.getAttacker().getName() + " after first confront:");
        System.out.println(con.getAttacker().getLife());
        System.out.println(con.getAttacker().getDefense());
        System.out.println(con.getAttacker().getReiatsu());
        System.out.println("Alive: "+ con.getAttacker().isAlive());
        System.out.println(con.getTarget().getName() + " after fisrt confront:");
        System.out.println(con.getTarget().getLife());
        System.out.println(con.getTarget().getDefense());
        System.out.println(con.getTarget().getReiatsu());
        System.out.println("Alive: "+ con.getTarget().isAlive());

        Confront con2 = new Confront();
        con2.setAttacker(sub);
        con2.setTarget(e1);
        con2.setAttackerPower(s3);
        con2.setGoal("Rescue Orihime");
        System.out.println("-----Confront-----");
        System.out.println("Kurosaki Ichigo attacks Ulquiorra");
        System.out.println("Goal:" + con2.getGoal());
        System.out.println(con2.getAttacker().getName() + " before second confront:");
        System.out.println(con2.getAttacker().getLife());
        System.out.println(con2.getAttacker().getDefense());
        System.out.println(con2.getAttacker().getReiatsu());
        System.out.println("Alive: "+ con2.getAttacker().isAlive());
        System.out.println(con2.getTarget().getName() + " before second confront:");
        System.out.println(con2.getTarget().getLife());
        System.out.println(con2.getTarget().getDefense());
        System.out.println(con2.getTarget().getReiatsu());
        System.out.println("Alive: "+ con2.getTarget().isAlive());
        System.out.println(con2.getAttacker().getName() + " uses " + con2.getAttackerPower().getName());
        con2.action();
        System.out.println(con2.getAttacker().getName() + " after second confront:");
        System.out.println(con2.getAttacker().getLife());
        System.out.println(con2.getAttacker().getDefense());
        System.out.println(con2.getAttacker().getReiatsu());
        System.out.println("Alive: "+ con2.getAttacker().isAlive());
        System.out.println(con2.getTarget().getName() + " after second confront:");
        System.out.println(con2.getTarget().getLife());
        System.out.println(con2.getTarget().getDefense());
        System.out.println(con2.getTarget().getReiatsu());
        System.out.println("Alive: "+ con2.getTarget().isAlive());
        con2.setAttackerPower(s4);
        System.out.println("Last attack!!!");
        System.out.println(con2.getAttacker().getName() + " uses " + con2.getAttackerPower().getName());
        con2.action();
        System.out.println(con2.getAttacker().getName() + " after third confront:");
        System.out.println(con2.getAttacker().getLife());
        System.out.println(con2.getAttacker().getDefense());
        System.out.println(con2.getAttacker().getReiatsu());
        System.out.println("Alive: "+ con2.getAttacker().isAlive());
        System.out.println(con2.getTarget().getName() + " after third confront:");
        System.out.println(con2.getTarget().getLife());
        System.out.println(con2.getTarget().getDefense());
        System.out.println(con2.getTarget().getReiatsu());
        System.out.println("Alive: "+ con2.getTarget().isAlive());

        System.out.println("Orihime, now free, cures Ichigo and herself");
        System.out.println(h1.getName() + " before cure:");
        System.out.println(h1.getLife());
        System.out.println(h1.getReiatsu());
        System.out.println("(((after cure)))");
        h1.useAbility(sp1, sub);
        h1.useAbility(sp1, h1);
        System.out.println(sub.getName() + " : ");
        System.out.println(sub.getLife());
        System.out.println(sub.getReiatsu());
        System.out.println(h1.getName() + " : ");
        System.out.println(h1.getLife());
        System.out.println(h1.getReiatsu());


        System.out.println("-----Division 11-----");
        System.out.println(d1.getSpecialty());
        for(NormalShinigami n : d1.getMembers()) System.out.println(n.getRank() + " : "+ n.getName());

        System.out.println("-----SoulSociety-----");
        System.out.println(sou == sou2);
        for(Creature c : sou.getInhabtants()) System.out.println(c.getName());

        System.out.println("-----HumanWorld-----");
        System.out.println(hw == hw1);
        for(Creature c : hw.getInhabtants()) System.out.println(c.getName());

        System.out.println("-----HuecoMundo-----");
        System.out.println(hueco == hueco2);
        for(Creature c : hueco.getInhabtants()) System.out.println(c.getName());
    }
}